// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTXServer.Data;

#nullable disable

namespace ProjectTXServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            RoleId = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd"
                        },
                        new
                        {
                            UserId = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            RoleId = "360E601E-92F2-4F08-832B-604A21293258"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectTXServer.Entity.AreaLocation", b =>
                {
                    b.Property<int>("LocateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocateId"), 1L, 1);

                    b.Property<string>("LocateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocateId");

                    b.ToTable("Area", (string)null);

                    b.HasData(
                        new
                        {
                            LocateId = 1,
                            LocateName = "TP.HCM"
                        },
                        new
                        {
                            LocateId = 2,
                            LocateName = "Hà Nội"
                        },
                        new
                        {
                            LocateId = 3,
                            LocateName = "Đà Nẵng"
                        },
                        new
                        {
                            LocateId = 4,
                            LocateName = "Trà Vinh"
                        },
                        new
                        {
                            LocateId = 5,
                            LocateName = "Nha Trang"
                        },
                        new
                        {
                            LocateId = 6,
                            LocateName = "Vĩnh Phúc"
                        },
                        new
                        {
                            LocateId = 7,
                            LocateName = "An Giang"
                        },
                        new
                        {
                            LocateId = 8,
                            LocateName = "Cần Thơ"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.GenderType", b =>
                {
                    b.Property<string>("GenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("GenderType", (string)null);

                    b.HasData(
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            GenderName = "Man"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            GenderName = "Women"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AreaLocationLocateId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIntro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("real");

                    b.Property<int>("ProductRate")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("AreaLocationLocateId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = "66669eb6-6366-4d97-8271-6542bf88d425",
                            ProductCover = "css/images/product_men1.PNG",
                            ProductDescription = "This is BST Product",
                            ProductIntro = "link clip",
                            ProductName = "The Astronut",
                            ProductPrice = 80000f,
                            ProductRate = 1
                        },
                        new
                        {
                            ProductId = "5404f3dd-9d6f-41eb-a74a-c84d87a56608",
                            ProductCover = "css/images/product_men2.PNG",
                            ProductDescription = "Men T-shirt The Astronut",
                            ProductIntro = "link clip",
                            ProductName = "BST Summer T-shirt",
                            ProductPrice = 120000f,
                            ProductRate = 1
                        },
                        new
                        {
                            ProductId = "d3db9d49-ea86-4b1c-a365-979fdd04f1bc",
                            ProductCover = "css/images/product_men3.PNG",
                            ProductDescription = "The King man T shirt make by coton",
                            ProductIntro = "link clip",
                            ProductName = "King man T shirt",
                            ProductPrice = 1400000f,
                            ProductRate = 3
                        },
                        new
                        {
                            ProductId = "a5fb324a-c75a-4b17-964a-30e9187c1270",
                            ProductCover = "css/images/product_men4.PNG",
                            ProductDescription = "The Anti formalism T-shirt for men",
                            ProductIntro = "link clip",
                            ProductName = "Anti formalism",
                            ProductPrice = 4400000f,
                            ProductRate = 3
                        },
                        new
                        {
                            ProductId = "5c92efa7-9e2e-4185-8da4-5ed79bdfedcf",
                            ProductCover = "css/images/product_men5.PNG",
                            ProductDescription = "This is Unifas",
                            ProductIntro = "link clip",
                            ProductName = "Unifas",
                            ProductPrice = 5400000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "108a0d71-bd7c-4247-8052-79cf34da30fa",
                            ProductCover = "css/images/product_men6.PNG",
                            ProductDescription = "Make in china",
                            ProductIntro = "link clip",
                            ProductName = "T shirt for men",
                            ProductPrice = 140000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "f537de7f-c04a-4a7f-bf8a-43c530d40b99",
                            ProductCover = "css/images/product_men7.PNG",
                            ProductDescription = "This is YourName Product",
                            ProductIntro = "link clip",
                            ProductName = "YourName",
                            ProductPrice = 1600000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "1785cfb4-8c6c-4edf-8fc6-ae004e9145ad",
                            ProductCover = "css/images/product_men8.PNG",
                            ProductDescription = "T-shirt smile, that is the best for you",
                            ProductIntro = "link clip",
                            ProductName = "T-shirt smile",
                            ProductPrice = 6400000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "d69e5e7a-4725-46a8-96a4-0fd61559ba6a",
                            ProductCover = "css/images/product_men9.PNG",
                            ProductDescription = "True choise for guy",
                            ProductIntro = "link clip",
                            ProductName = "Magic T-shirt",
                            ProductPrice = 740000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "ce38bd82-7d36-4046-b173-d98f0995490a",
                            ProductCover = "css/images/product_men10.PNG",
                            ProductDescription = "That is Astronaut",
                            ProductIntro = "link clip",
                            ProductName = "Astronaut",
                            ProductPrice = 96000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "10c6f609-a376-4654-9e54-772a011774bc",
                            ProductCover = "css/images/product_women1.PNG",
                            ProductDescription = "Headsfer T-shirt for women1 have a passion with SWAG",
                            ProductIntro = "link clip",
                            ProductName = "women1",
                            ProductPrice = 990000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "a232bb1a-f1f7-4929-9307-a1a8e3b0a90e",
                            ProductCover = "css/images/product_women2.PNG",
                            ProductDescription = "This is women2",
                            ProductIntro = "link clip",
                            ProductName = "women2",
                            ProductPrice = 670000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "e2f1cf08-e94e-49c8-a095-1cac23e23aa3",
                            ProductCover = "css/images/product_women3.PNG",
                            ProductDescription = "This is women3",
                            ProductIntro = "link clip",
                            ProductName = "women3",
                            ProductPrice = 450000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "b71b9324-77be-4d5b-8725-c3c1bd82fca5",
                            ProductCover = "css/images/product_women4.PNG",
                            ProductDescription = "This is women4",
                            ProductIntro = "link clip",
                            ProductName = "women4",
                            ProductPrice = 350000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "174b1d16-35bc-4d07-9c76-8772f23309ef",
                            ProductCover = "css/images/product_women5.PNG",
                            ProductDescription = "This is women5",
                            ProductIntro = "link clip",
                            ProductName = "women5",
                            ProductPrice = 950000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "cdf3b598-3c66-4de5-a774-5a055cb3aaa5",
                            ProductCover = "css/images/product_women6.PNG",
                            ProductDescription = "This is women6",
                            ProductIntro = "link clip",
                            ProductName = "women6",
                            ProductPrice = 4250000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "cf6ef659-8813-4374-bc65-c161aefe8e60",
                            ProductCover = "css/images/product_women7.PNG",
                            ProductDescription = "This is women7",
                            ProductIntro = "link clip",
                            ProductName = "women7",
                            ProductPrice = 6750000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "b7ce2d18-0dfa-4281-847e-3c03806eedce",
                            ProductCover = "css/images/product_women8.PNG",
                            ProductDescription = "This is women8",
                            ProductIntro = "link clip",
                            ProductName = "women8",
                            ProductPrice = 150000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "38928510-eb25-4373-8adf-c8f20c7ee534",
                            ProductCover = "css/images/product_women9.PNG",
                            ProductDescription = "This is women9",
                            ProductIntro = "link clip",
                            ProductName = "women9",
                            ProductPrice = 45000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "fb0f49e1-e65f-448e-842a-561d2c18a7a1",
                            ProductCover = "css/images/product_women10.PNG",
                            ProductDescription = "This is women10",
                            ProductIntro = "link clip",
                            ProductName = "women10",
                            ProductPrice = 99000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "02a3ed08-9f18-4fd9-9789-fa95114865de",
                            ProductCover = "css/images/product_pantmen1.PNG",
                            ProductDescription = "This is pantman1",
                            ProductIntro = "link clip",
                            ProductName = "pantman1",
                            ProductPrice = 870000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "f799531e-8ec5-491b-be3a-01590ffc8bcb",
                            ProductCover = "css/images/product_pantmen2.PNG",
                            ProductDescription = "This is pantman2",
                            ProductIntro = "link clip",
                            ProductName = "pantman2",
                            ProductPrice = 1400000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "93492ed7-443d-4efa-937e-dcb189dbd657",
                            ProductCover = "css/images/product_pantmen3.PNG",
                            ProductDescription = "This is pantman3",
                            ProductIntro = "link clip",
                            ProductName = "pantman3",
                            ProductPrice = 1900000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "1c71cb12-68b8-4c8f-bd07-1ffdeca30f61",
                            ProductCover = "css/images/product_pantmen4.PNG",
                            ProductDescription = "This is pantman4",
                            ProductIntro = "link clip",
                            ProductName = "pantman4",
                            ProductPrice = 8000000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "de04143d-5165-4f28-ba59-d9a6fbe4281b",
                            ProductCover = "css/images/product_pantmen5.PNG",
                            ProductDescription = "This is pantman5",
                            ProductIntro = "link clip",
                            ProductName = "pantman5",
                            ProductPrice = 980000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "f798f4eb-06ba-4150-8a6c-78c93c0ab85a",
                            ProductCover = "css/images/product_pantwomen1.PNG",
                            ProductDescription = "This is pantwoman1",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman1",
                            ProductPrice = 96000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "9d2891fd-98e8-44ea-af70-4b2dcc11c9f7",
                            ProductCover = "css/images/product_pantwomen2.PNG",
                            ProductDescription = "This is pantwoman2",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman2",
                            ProductPrice = 4890000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "98dc195f-ba34-4668-ba27-ce9e0939a0cb",
                            ProductCover = "css/images/product_pantwomen3.PNG",
                            ProductDescription = "This is pantwoman3",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman3",
                            ProductPrice = 234000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "2551fe50-6fb7-4f30-ac87-7f80186b475e",
                            ProductCover = "css/images/product_pantwomen4.PNG",
                            ProductDescription = "This is pantwoman4",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman4",
                            ProductPrice = 866000f,
                            ProductRate = 5
                        },
                        new
                        {
                            ProductId = "0bc1e240-bb69-457b-8af3-c7ef825446da",
                            ProductCover = "css/images/product_pantwomen5.PNG",
                            ProductDescription = "This is pantwoman5",
                            ProductIntro = "link clip",
                            ProductName = "pantwoman5",
                            ProductPrice = 477000f,
                            ProductRate = 5
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInGender", b =>
                {
                    b.Property<string>("GenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GenderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInGender", (string)null);

                    b.HasData(
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "66669eb6-6366-4d97-8271-6542bf88d425"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "5404f3dd-9d6f-41eb-a74a-c84d87a56608"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "d3db9d49-ea86-4b1c-a365-979fdd04f1bc"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "a5fb324a-c75a-4b17-964a-30e9187c1270"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "5c92efa7-9e2e-4185-8da4-5ed79bdfedcf"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "108a0d71-bd7c-4247-8052-79cf34da30fa"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "f537de7f-c04a-4a7f-bf8a-43c530d40b99"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "1785cfb4-8c6c-4edf-8fc6-ae004e9145ad"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "d69e5e7a-4725-46a8-96a4-0fd61559ba6a"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "ce38bd82-7d36-4046-b173-d98f0995490a"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "10c6f609-a376-4654-9e54-772a011774bc"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "a232bb1a-f1f7-4929-9307-a1a8e3b0a90e"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "e2f1cf08-e94e-49c8-a095-1cac23e23aa3"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "b71b9324-77be-4d5b-8725-c3c1bd82fca5"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "174b1d16-35bc-4d07-9c76-8772f23309ef"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "cdf3b598-3c66-4de5-a774-5a055cb3aaa5"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "cf6ef659-8813-4374-bc65-c161aefe8e60"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "b7ce2d18-0dfa-4281-847e-3c03806eedce"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "38928510-eb25-4373-8adf-c8f20c7ee534"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "fb0f49e1-e65f-448e-842a-561d2c18a7a1"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "02a3ed08-9f18-4fd9-9789-fa95114865de"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "f799531e-8ec5-491b-be3a-01590ffc8bcb"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "93492ed7-443d-4efa-937e-dcb189dbd657"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "1c71cb12-68b8-4c8f-bd07-1ffdeca30f61"
                        },
                        new
                        {
                            GenderId = "98121c51-bfde-49a7-b501-0c2a1e2924af",
                            ProductId = "de04143d-5165-4f28-ba59-d9a6fbe4281b"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "f798f4eb-06ba-4150-8a6c-78c93c0ab85a"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "9d2891fd-98e8-44ea-af70-4b2dcc11c9f7"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "98dc195f-ba34-4668-ba27-ce9e0939a0cb"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "2551fe50-6fb7-4f30-ac87-7f80186b475e"
                        },
                        new
                        {
                            GenderId = "ea066ee9-33cd-4007-9e9b-a49ee06f0048",
                            ProductId = "0bc1e240-bb69-457b-8af3-c7ef825446da"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInLocation", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LocateId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "LocateId");

                    b.HasIndex("LocateId");

                    b.ToTable("ProductInLocation", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = "66669eb6-6366-4d97-8271-6542bf88d425",
                            LocateId = 1
                        },
                        new
                        {
                            ProductId = "5404f3dd-9d6f-41eb-a74a-c84d87a56608",
                            LocateId = 2
                        },
                        new
                        {
                            ProductId = "d3db9d49-ea86-4b1c-a365-979fdd04f1bc",
                            LocateId = 3
                        },
                        new
                        {
                            ProductId = "a5fb324a-c75a-4b17-964a-30e9187c1270",
                            LocateId = 4
                        },
                        new
                        {
                            ProductId = "5c92efa7-9e2e-4185-8da4-5ed79bdfedcf",
                            LocateId = 5
                        },
                        new
                        {
                            ProductId = "108a0d71-bd7c-4247-8052-79cf34da30fa",
                            LocateId = 6
                        },
                        new
                        {
                            ProductId = "f537de7f-c04a-4a7f-bf8a-43c530d40b99",
                            LocateId = 7
                        },
                        new
                        {
                            ProductId = "1785cfb4-8c6c-4edf-8fc6-ae004e9145ad",
                            LocateId = 8
                        },
                        new
                        {
                            ProductId = "d69e5e7a-4725-46a8-96a4-0fd61559ba6a",
                            LocateId = 1
                        },
                        new
                        {
                            ProductId = "ce38bd82-7d36-4046-b173-d98f0995490a",
                            LocateId = 2
                        },
                        new
                        {
                            ProductId = "10c6f609-a376-4654-9e54-772a011774bc",
                            LocateId = 3
                        },
                        new
                        {
                            ProductId = "a232bb1a-f1f7-4929-9307-a1a8e3b0a90e",
                            LocateId = 4
                        },
                        new
                        {
                            ProductId = "e2f1cf08-e94e-49c8-a095-1cac23e23aa3",
                            LocateId = 5
                        },
                        new
                        {
                            ProductId = "b71b9324-77be-4d5b-8725-c3c1bd82fca5",
                            LocateId = 6
                        },
                        new
                        {
                            ProductId = "174b1d16-35bc-4d07-9c76-8772f23309ef",
                            LocateId = 7
                        },
                        new
                        {
                            ProductId = "cdf3b598-3c66-4de5-a774-5a055cb3aaa5",
                            LocateId = 8
                        },
                        new
                        {
                            ProductId = "cf6ef659-8813-4374-bc65-c161aefe8e60",
                            LocateId = 1
                        },
                        new
                        {
                            ProductId = "b7ce2d18-0dfa-4281-847e-3c03806eedce",
                            LocateId = 2
                        },
                        new
                        {
                            ProductId = "38928510-eb25-4373-8adf-c8f20c7ee534",
                            LocateId = 3
                        },
                        new
                        {
                            ProductId = "fb0f49e1-e65f-448e-842a-561d2c18a7a1",
                            LocateId = 4
                        },
                        new
                        {
                            ProductId = "02a3ed08-9f18-4fd9-9789-fa95114865de",
                            LocateId = 5
                        },
                        new
                        {
                            ProductId = "f799531e-8ec5-491b-be3a-01590ffc8bcb",
                            LocateId = 6
                        },
                        new
                        {
                            ProductId = "93492ed7-443d-4efa-937e-dcb189dbd657",
                            LocateId = 7
                        },
                        new
                        {
                            ProductId = "1c71cb12-68b8-4c8f-bd07-1ffdeca30f61",
                            LocateId = 8
                        },
                        new
                        {
                            ProductId = "de04143d-5165-4f28-ba59-d9a6fbe4281b",
                            LocateId = 1
                        },
                        new
                        {
                            ProductId = "f798f4eb-06ba-4150-8a6c-78c93c0ab85a",
                            LocateId = 2
                        },
                        new
                        {
                            ProductId = "9d2891fd-98e8-44ea-af70-4b2dcc11c9f7",
                            LocateId = 3
                        },
                        new
                        {
                            ProductId = "98dc195f-ba34-4668-ba27-ce9e0939a0cb",
                            LocateId = 4
                        },
                        new
                        {
                            ProductId = "2551fe50-6fb7-4f30-ac87-7f80186b475e",
                            LocateId = 5
                        },
                        new
                        {
                            ProductId = "0bc1e240-bb69-457b-8af3-c7ef825446da",
                            LocateId = 6
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInProductType", b =>
                {
                    b.Property<string>("ProductTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductTypeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInProductType", (string)null);

                    b.HasData(
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "66669eb6-6366-4d97-8271-6542bf88d425"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "5404f3dd-9d6f-41eb-a74a-c84d87a56608"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "d3db9d49-ea86-4b1c-a365-979fdd04f1bc"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "a5fb324a-c75a-4b17-964a-30e9187c1270"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "5c92efa7-9e2e-4185-8da4-5ed79bdfedcf"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "108a0d71-bd7c-4247-8052-79cf34da30fa"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "f537de7f-c04a-4a7f-bf8a-43c530d40b99"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "1785cfb4-8c6c-4edf-8fc6-ae004e9145ad"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "d69e5e7a-4725-46a8-96a4-0fd61559ba6a"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "ce38bd82-7d36-4046-b173-d98f0995490a"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "10c6f609-a376-4654-9e54-772a011774bc"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "a232bb1a-f1f7-4929-9307-a1a8e3b0a90e"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "e2f1cf08-e94e-49c8-a095-1cac23e23aa3"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "b71b9324-77be-4d5b-8725-c3c1bd82fca5"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "174b1d16-35bc-4d07-9c76-8772f23309ef"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "cdf3b598-3c66-4de5-a774-5a055cb3aaa5"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "cf6ef659-8813-4374-bc65-c161aefe8e60"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "b7ce2d18-0dfa-4281-847e-3c03806eedce"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "38928510-eb25-4373-8adf-c8f20c7ee534"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductId = "fb0f49e1-e65f-448e-842a-561d2c18a7a1"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "02a3ed08-9f18-4fd9-9789-fa95114865de"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "f799531e-8ec5-491b-be3a-01590ffc8bcb"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "93492ed7-443d-4efa-937e-dcb189dbd657"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "1c71cb12-68b8-4c8f-bd07-1ffdeca30f61"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "de04143d-5165-4f28-ba59-d9a6fbe4281b"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "f798f4eb-06ba-4150-8a6c-78c93c0ab85a"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "9d2891fd-98e8-44ea-af70-4b2dcc11c9f7"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "98dc195f-ba34-4668-ba27-ce9e0939a0cb"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "2551fe50-6fb7-4f30-ac87-7f80186b475e"
                        },
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductId = "0bc1e240-bb69-457b-8af3-c7ef825446da"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductType", b =>
                {
                    b.Property<string>("ProductTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductTypeId");

                    b.ToTable("ProductType", (string)null);

                    b.HasData(
                        new
                        {
                            ProductTypeId = "de113193-41e2-48a9-9862-2ba31bcf1816",
                            ProductTypeName = "Pants"
                        },
                        new
                        {
                            ProductTypeId = "44841efa-a3ae-4dc9-9699-8ccd89a79f7d",
                            ProductTypeName = "Shirt"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.AppRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AppRole");

                    b.HasData(
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb4fd",
                            ConcurrencyStamp = "2f94b13b-8304-4036-a240-8a11185dcc55",
                            Name = "Staff",
                            NormalizedName = "staff",
                            Description = "Staff"
                        },
                        new
                        {
                            Id = "360E601E-92F2-4F08-832B-604A21293258",
                            ConcurrencyStamp = "db8872a7-46f9-4f0b-9819-e297d69854bc",
                            Name = "Admin",
                            NormalizedName = "admin",
                            Description = "Admin"
                        });
                });

            modelBuilder.Entity("ProjectTXServer.Entity.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<byte[]>("PasswordHashs")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UserDoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AppUser");

                    b.HasData(
                        new
                        {
                            Id = "DE544998-A3CC-4E12-ABB4-0642E57BD222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a98cc324-8cfa-4b9e-ba86-b0f9fe9fcfd5",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f6083f9-c0f0-49af-911e-717c1e04d14a",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            PasswordHashs = new byte[] { 97, 44, 41, 103, 196, 188, 200, 0, 9, 59, 166, 54, 144, 5, 212, 53, 118, 185, 244, 59, 152, 119, 175, 129, 24, 191, 90, 235, 205, 80, 133, 95, 164, 203, 51, 224, 36, 21, 40, 13, 92, 237, 15, 193, 0, 5, 191, 108, 219, 225, 31, 244, 173, 229, 238, 55, 16, 206, 224, 141, 95, 100, 190, 157 },
                            PasswordSalt = new byte[] { 154, 65, 102, 153, 217, 8, 65, 219, 183, 144, 88, 172, 134, 251, 42, 52, 180, 43, 174, 39, 198, 250, 202, 141, 1, 81, 84, 27, 155, 44, 130, 45, 246, 126, 91, 189, 194, 156, 124, 33, 101, 189, 57, 10, 5, 83, 160, 227, 240, 10, 11, 37, 114, 40, 221, 243, 70, 144, 234, 235, 185, 117, 114, 93, 8, 89, 42, 71, 14, 19, 103, 141, 67, 1, 157, 17, 37, 199, 162, 149, 103, 235, 140, 163, 62, 252, 127, 253, 155, 183, 81, 239, 122, 162, 182, 88, 84, 45, 7, 107, 245, 28, 252, 228, 56, 52, 36, 130, 46, 194, 69, 181, 204, 137, 19, 168, 206, 129, 156, 116, 4, 33, 49, 206, 185, 91, 155, 190 },
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserDoB = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserFirstName = "admin first name",
                            UserLastName = "admin last name",
                            UserPhoneNumber = "08658568790"
                        },
                        new
                        {
                            Id = "f49e4348-718f-43e3-b1f6-6dc89c5Bb5ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82ddafc9-ddbe-41b3-a797-34b51a825e10",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "601fa554-e87c-47c3-a910-2af406d499d0",
                            TwoFactorEnabled = false,
                            UserName = "Staff",
                            PasswordHashs = new byte[] { 97, 44, 41, 103, 196, 188, 200, 0, 9, 59, 166, 54, 144, 5, 212, 53, 118, 185, 244, 59, 152, 119, 175, 129, 24, 191, 90, 235, 205, 80, 133, 95, 164, 203, 51, 224, 36, 21, 40, 13, 92, 237, 15, 193, 0, 5, 191, 108, 219, 225, 31, 244, 173, 229, 238, 55, 16, 206, 224, 141, 95, 100, 190, 157 },
                            PasswordSalt = new byte[] { 154, 65, 102, 153, 217, 8, 65, 219, 183, 144, 88, 172, 134, 251, 42, 52, 180, 43, 174, 39, 198, 250, 202, 141, 1, 81, 84, 27, 155, 44, 130, 45, 246, 126, 91, 189, 194, 156, 124, 33, 101, 189, 57, 10, 5, 83, 160, 227, 240, 10, 11, 37, 114, 40, 221, 243, 70, 144, 234, 235, 185, 117, 114, 93, 8, 89, 42, 71, 14, 19, 103, 141, 67, 1, 157, 17, 37, 199, 162, 149, 103, 235, 140, 163, 62, 252, 127, 253, 155, 183, 81, 239, 122, 162, 182, 88, 84, 45, 7, 107, 245, 28, 252, 228, 56, 52, 36, 130, 46, 194, 69, 181, 204, 137, 19, 168, 206, 129, 156, 116, 4, 33, 49, 206, 185, 91, 155, 190 },
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserDoB = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserFirstName = "staff first name",
                            UserLastName = "staff last name",
                            UserPhoneNumber = "08658568790"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTXServer.Entity.Product", b =>
                {
                    b.HasOne("ProjectTXServer.Entity.AreaLocation", null)
                        .WithMany("ProductInLocation")
                        .HasForeignKey("AreaLocationLocateId");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInGender", b =>
                {
                    b.HasOne("ProjectTXServer.Entity.GenderType", "GenderObj")
                        .WithMany("ListGender")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTXServer.Entity.Product", "ProductObj")
                        .WithMany("ListProductGender")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenderObj");

                    b.Navigation("ProductObj");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInLocation", b =>
                {
                    b.HasOne("ProjectTXServer.Entity.AreaLocation", "LocationObj")
                        .WithMany("ListProductLocation")
                        .HasForeignKey("LocateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTXServer.Entity.Product", "ProductObj")
                        .WithMany("ListProductLocation")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationObj");

                    b.Navigation("ProductObj");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductInProductType", b =>
                {
                    b.HasOne("ProjectTXServer.Entity.Product", "ProductObj")
                        .WithMany("ListProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTXServer.Entity.ProductType", "ProductTypeObj")
                        .WithMany("ListType")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductObj");

                    b.Navigation("ProductTypeObj");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.AreaLocation", b =>
                {
                    b.Navigation("ListProductLocation");

                    b.Navigation("ProductInLocation");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.GenderType", b =>
                {
                    b.Navigation("ListGender");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.Product", b =>
                {
                    b.Navigation("ListProduct");

                    b.Navigation("ListProductGender");

                    b.Navigation("ListProductLocation");
                });

            modelBuilder.Entity("ProjectTXServer.Entity.ProductType", b =>
                {
                    b.Navigation("ListType");
                });
#pragma warning restore 612, 618
        }
    }
}
